SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio AS euros, precio* 1.18 AS dolares FROM producto;
SELECT nombre AS nombre_producto, precio AS euros, precio * 1.18 AS dolares FROM producto;
SELECT UPPER(nombre) AS nombre_en_mayusculas, precio FROM producto;
SELECT LOWER(nombre) AS nombre_en_minuscula, precio FROM producto;
SELECT nombre, UPPER(SUBSTRING(nombre, 1, 2)) AS fabricante_mayusculas FROM fabricante;
SELECT nombre, ROUND(precio) AS precio_redondeado FROM producto;
SELECT nombre, TRUNCATE(precio, 0) AS precio_sin_decimales FROM producto;
SELECT DISTINCT f.codigo FROM fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante;
SELECT DISTINCT f.codigo FROM fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 2 OFFSET 3;
SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT p.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.codigo = 2;
SELECT p.nombre, p.precio, f.nombre AS nombre_fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE p.precio = (SELECT MIN(precio) FROM producto);
SELECT p.nombre, p.precio FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Crucial' AND p.precio > 200;